### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by Giodga** [k3zi/BelievaBoat#1]
When I'm trying to run it I get an error

client.potentialBots = config.extraTokens.map((token, i) => {
                                                                   ^ (this arrow is pointing at map)

TypeError: Cannot read property 'map' of undefined
    at Object.<anonymous> (C:\Users\...myloaction)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by k3zi** [comment]
Should be fixed once a `config.json` is created from the `config.example.json` template.
